### ISSUE TITLE
Google Signin Error Status code :10 (DEVELOPER_ERROR)

### ISSUE THREAD

**Issue by sabdar18** [UdacityAndroidBasicsScholarship/wmn-safety#42]
check out the link  for futher 
https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes.html#DEVELOPER_ERROR

**Comment by kkdroidgit** [comment]
@sabdar18 We have not implemented `Google Sign in` till now in our `development` or `master` branch. Can you explain more on the issue?

**Comment by kartikohri1712** [comment]
@sabdar18 You maybe facing the error because your debug keystore's SHA fingerprint is not added to Firebase project.
