### ISSUE TITLE
update profile name and phone number to firebase 

### ISSUE THREAD

**Issue by sabdar18** [UdacityAndroidBasicsScholarship/wmn-safety#49]
#47 

@kartikohri1712 @kkdroidgit @piedcipher
a bug in signup Activity , need to update profile name and update phone number to the firebase
as we are taking name, email,phone password as fields , but in the code using email and password to create account after that need to update profile name , and also phone number

**Comment by kartikohri1712** [comment]
@sabdar18 We are aware of the issue but we are yet deciding on the data model to store the data. Once the data model, is finalized it will be added.

**Comment by sabdar18** [comment]
@kartikohri1712  yes defintely a good Idea.
But need to update atleast name (apart from phone number, which is some complex like verification is there for this using otp) 

check out this [link ](https://firebase.google.com/docs/auth/android/manage-users#update_a_users_profile). 
It will be useful when the user loggedin , he will atleast find his name entered during signup, in his profile

**Comment by kartikohri1712** [comment]
#87
